app = "perpx"
primary_region = "iad"

[build]
  dockerfile = "fly/Dockerfile"

[env]
  NODE_ENV = "production"
  ENVIRONMENT = "production"
  NODE_OPTIONS = "--dns-result-order=ipv4first"
  BACKEND_PORT = "3001"
  WS_PORT = "3002"

[http_service]
  internal_port = 80
  force_https = true

  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "20s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "bun --cwd /app/packages/db prisma migrate deploy --schema=prisma/schema.prisma"